version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    restart: unless-stopped

  webdash:
    build:
      context: ./webapp
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://api:5000/predict
    depends_on:
      - api
    restart: unless-stopped